Make CI fail with warnings

diff --git a/.github/workflows/ci-linux.yaml b/.github/workflows/ci-linux.yaml
--- a/.github/workflows/ci-linux.yaml
+++ b/.github/workflows/ci-linux.yaml
@@ -133,17 +133,44 @@ jobs:
           use-gha-cache: false
 
       - name: Build server system
+        shell: bash
         run: |
+          set -euo pipefail
+
+          error=0
+
           echo "Logging in..."
           nix shell nixpkgs#attic-client --command attic login fred http://192.168.31.14:8080 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIxNDgyMzMyODksIm5iZiI6MTc2OTU0MjA4OSwic3ViIjoiZnJlZCIsImh0dHBzOi8vand0LmF0dGljLnJzL3YxIjp7ImNhY2hlcyI6eyJmcmVkIjp7InIiOjEsInciOjEsImNjIjoxfX19fQ.WhR5ixdW0j-wV77Tl8VubJPEyEvgQ8nQWYbgJxI8pPiLJN6v4DVaqKPu15mcY0N0B0zKnq9-njG5EOn2Z2-4dMgfx9ttTA-lltxrvPf5nKR9zAXg6hgPYsnGQuRFBvAFzlfPCpcIU2rgEVzMajzjipQgfUnVPDuto9uPU1VG25fncVRYz5dUhOXTfvN_WWpzcgQ7HDHQufbui5IoG-nmFMFWcNkxTCw7XVNs1PYFpadMGn6zAeh9Hi6epYYllr1aTcmTCx6ut3-fbFdQaxGG_HsCyxFiIf9r6GNSQvZOeHbeLcE21RQ6qNrkKZuQiVoOAcQr7ngpQ2jjcWnajw_hCPi6rqByZxdZy8IAbPQ83nm9o5UlfKg99sr6YSV-6ZTBvsOm-ioUX9hSktWm3O7cdH74ygmbUC_QL-os6aYNhbyQjSEMgiOpS65VnFURG58gnnvVHncMvohyDKwZqcWVtiaQApNeL3_LEATtX_zdqlaWdCVXO3t3QlD0ebYVhb4rn2KEg0GOZHGpWPqJnszRSMwXgWM1fG37OF117Qz6O9280BoEMdjLvITr5Cq0kQqS0PzapLdI5maU6ZluyqvAvgqdHzwjey4hDDq3FjITA_JMUStRlH7sMwtaSGTiTTOHQPe7WT9PImqfm4G8Q3urOsHMBE_Au1dqnUz4Lq-yU4M
+
+          : > build.stderr
+
           echo "Building server: ${{ matrix.system }}"
-          nix build ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel"
+          nix build ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel" 2> >(tee build.stderr >&2)
+
+          if grep -qE "evaluation warning:" build.stderr; then
+            error=1
+          fi
+
           echo "Pushing first result..."
           nix shell nixpkgs#attic-client --command attic push fred result --ignore-upstream-cache-filter -j 2
-          nix build ".#nixosConfigurations.${{ matrix.system }}.config.home-manager.users.fred.home.activationPackage"
+
+          : > build.stderr
+          echo "Building home-manager for: ${{ matrix.system }}"
+          nix build ".#nixosConfigurations.${{ matrix.system }}.config.home-manager.users.fred.home.activationPackage" 2> >(tee build.stderr >&2)
+
+          if grep -qE "evaluation warning:" build.stderr; then
+            error=1
+          fi
+
           echo "Pushing second result..."
           nix shell nixpkgs#attic-client --command attic push fred result --ignore-upstream-cache-filter -j 2
 
+          if [ "$error" -ne 0 ]; then
+            echo "One or more warnings were detected during the build."
+
+            echo "::error::Nix evaluation warnings detected"
+            exit 1
+          fi
   # =====================================================================
   # Build desktop systems
   # =====================================================================
@@ -178,16 +205,44 @@ jobs:
           use-gha-cache: false
 
       - name: Build desktop system
+        shell: bash
         run: |
+          set -euo pipefail
+
+          error=0
+
           echo "Logging in..."
           nix shell nixpkgs#attic-client --command attic login fred http://192.168.31.14:8080 eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjIxNDgyMzMyODksIm5iZiI6MTc2OTU0MjA4OSwic3ViIjoiZnJlZCIsImh0dHBzOi8vand0LmF0dGljLnJzL3YxIjp7ImNhY2hlcyI6eyJmcmVkIjp7InIiOjEsInciOjEsImNjIjoxfX19fQ.WhR5ixdW0j-wV77Tl8VubJPEyEvgQ8nQWYbgJxI8pPiLJN6v4DVaqKPu15mcY0N0B0zKnq9-njG5EOn2Z2-4dMgfx9ttTA-lltxrvPf5nKR9zAXg6hgPYsnGQuRFBvAFzlfPCpcIU2rgEVzMajzjipQgfUnVPDuto9uPU1VG25fncVRYz5dUhOXTfvN_WWpzcgQ7HDHQufbui5IoG-nmFMFWcNkxTCw7XVNs1PYFpadMGn6zAeh9Hi6epYYllr1aTcmTCx6ut3-fbFdQaxGG_HsCyxFiIf9r6GNSQvZOeHbeLcE21RQ6qNrkKZuQiVoOAcQr7ngpQ2jjcWnajw_hCPi6rqByZxdZy8IAbPQ83nm9o5UlfKg99sr6YSV-6ZTBvsOm-ioUX9hSktWm3O7cdH74ygmbUC_QL-os6aYNhbyQjSEMgiOpS65VnFURG58gnnvVHncMvohyDKwZqcWVtiaQApNeL3_LEATtX_zdqlaWdCVXO3t3QlD0ebYVhb4rn2KEg0GOZHGpWPqJnszRSMwXgWM1fG37OF117Qz6O9280BoEMdjLvITr5Cq0kQqS0PzapLdI5maU6ZluyqvAvgqdHzwjey4hDDq3FjITA_JMUStRlH7sMwtaSGTiTTOHQPe7WT9PImqfm4G8Q3urOsHMBE_Au1dqnUz4Lq-yU4M
-          echo "Building server: ${{ matrix.system }}"
-          nix build ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel"
+
+          : > build.stderr
+
+          echo "Building desktop: ${{ matrix.system }}"
+          nix build ".#nixosConfigurations.${{ matrix.system }}.config.system.build.toplevel" 2> >(tee build.stderr >&2)
+
+          if grep -qE "evaluation warning:" build.stderr; then
+            error=1
+          fi
+
           echo "Pushing first result..."
           nix shell nixpkgs#attic-client --command attic push fred result --ignore-upstream-cache-filter -j 2
-          nix build ".#nixosConfigurations.${{ matrix.system }}.config.home-manager.users.fred.home.activationPackage"
+
+          : > build.stderr
+          echo "Building home-manager for: ${{ matrix.system }}"
+          nix build ".#nixosConfigurations.${{ matrix.system }}.config.home-manager.users.fred.home.activationPackage" 2> >(tee build.stderr >&2)
+
+          if grep -qE "evaluation warning:" build.stderr; then
+            error=1
+          fi
+
           echo "Pushing second result..."
           nix shell nixpkgs#attic-client --command attic push fred result --ignore-upstream-cache-filter -j 2
+
+          if [ "$error" -ne 0 ]; then
+            echo "One or more warnings were detected during the build."
+
+            echo "::error::Nix evaluation warnings detected"
+            exit 1
+          fi
 
   # =====================================================================
   # Required summary check
